version: "3"

services:
  mysql_serve:
    image: mysql:5.6.42
    container_name: micro_db_libros
    ports:
      - 33663:3306
    environment:
      MYSQL_USER: desarrollo
      MYSQL_PASSWORD: kevin123
      MYSQL_DATABASE: micro_books
      MYSQL_ROOT_PASSWORD: kevin123
  web:
    build: .
    container_name: micro_libros
    ports:
      - 8002:80
    volumes:
      - .:/opt/data
    links:
      - mysql_serve
